name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
      with:
        path: web  
    - name: Install frontend dependencies    
      run: yarn install
    - name: Run build task
      run: yarn build
    
    - uses: actions/checkout@v2     
      with:
        path: backend        
    - name: Install backend dependencies
      run: yarn install
    - name: Deploy to server
      run: |
        git remote add umbler https://geonosis.deploy.umbler.com/kqx7n25e/patricksuyti-com-br.git
        git push umbler master
        
      
      
      
